language: generic

sudo: false

matrix:
  include:
    - env: EMACS=emacs24
      addons:
        apt:
          sources: [ { sourceline: 'ppa:andreas-h/emacs' } ]
          packages: [ emacs24 ]
    - env: EMACS=emacs25
      addons:
        apt:
          sources: [ { sourceline: 'ppa:kelleyk/emacs' } ]
          packages: [ emacs25 ]

before_install:
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python

install:
  - export PATH=$HOME/.cask/bin:$PATH
  - cask

script:
  - $EMACS --version
  - cask exec ecukes --no-win -r magnars
